### ISSUE TITLE
Make API more "graph-like" to improve flexibility

### ISSUE THREAD

**Issue by pospi** [django-rea/rea-app#51]
The current API endpoints are all toplevel, which makes their usage sort of "REST-like". You can still combine them into single requests, but you can't use the same logic to query the same relationships for different parts of the graph.

As an example of what we're after, see [this commit in valuenetwork](https://github.com/FreedomCoop/valuenetwork/commit/3bef513118c9e279830fa964364189a7bad344e5).

I have done some experimentation and it seems that the `graphene.AbstractType`, `graphene.ObjectType` and `DjangoObjectType` base classes all serve the same interface- that is, they expose schemas which can define fields which refer to their own object fields, or relationship fields which refer to *other schemas*. I think binding to the other schemas is the remaining pattern we need to understand in order to build out the API how we want.

Something worth noting is that the main `schema.py` is aware in the API browser that `viewer`'s type is `ViewerQuery`, so there is something in there about how to bind a parent schema to a dynamic child one.

I suspect the implementation will be about defining the relationships to get from the parent to the child within the child's schema and then hooking up those queries from the parent. For example (and this could be incorrect), we might define a `has_member` field on `Agent` which accepts an `agent_id` for the member to check, and use that query from the toplevel viewer `Agent` to find all organisations of whom they are a member. Hopefully this makes enough sense to get discussion started.. it's bending my brain a bit.

**Comment by pospi** [comment]
You will have seen I've pushed some simple refactoring. I'm not sure if we need agent relationships and agent relationship roles to be queried directly (at least, not for querying agents; `allAgentRelationshipRoles` is totally valid for populating dropdowns). I expect these should be used internally to create the relationships exposed in VF terms by the graphQL API? Either way, I have moved them to their own schemas for consistency so that we can keep to 1 entity type per schema.

Something else I've begun to understand is the class signature for the graphene types (had to go work out what a metaclass was first). Basically all the classes you pass in are handled as base classes... and so you have to be careful not to use the same method / property names in schemas that you're going to attach at the same level, because you'll run into multiple inheritance issues if you do. This is why `Organisation.py` can call `self._load_own_agent()`, even though that method is declared in `Agent.py`- they both get passed to `ViewerQuery` and therefore you end up with a single class with all the base classes' methods on it. Ive found digging through the graphene code useful for working out what's going on here, specifically https://github.com/graphql-python/graphene-django/blob/master/graphene_django/types.py and https://github.com/graphql-python/graphene/blob/master/graphene/types. Now that I've seen how `DjangoObjectType` is implemented, it feels like the only reason we'd leverage that class is to control the output formatting of matches- probably all relationships are going to be easier coded onto `graphene.AbstractType` in order to use the core models' methods to load up the data.

Hopefully that makes some kind of sense, more coming when I've begun to setup a hierarchy... which is still melting my brain a bit!

**Comment by pospi** [comment]
Successfully have relationships working at multiple levels now. Check this query, which in addition to relationships also shows how the same relationships (`members` in this case) can be used at multiple anchor points:

```
fragment coreAgentFields on AgentBaseType {
  id
  name
  image
  note
  type
}

query($token: String) {
  viewer(token: $token) {
    # agent queries
    myAgent {
      ...coreAgentFields
      organizations {
        #...coreAgentFields
        id
        name
        members {
          #...coreAgentFields
          name
        }
      }
    }
    organization(id: 80) {
      ...coreAgentFields
      members {
        #...coreAgentFields
        name
      }
    }
  }
}
```

Note that all these entities (org, agent, member) are `EconomicAgents`, which is why the field set is declared against the base interface type I've set up. Should be able to improve it by giving the subtypes names (so that you can do the `on TypeName` syntax like in the Star Wars demos), but I'll leave that as an exercise for another day.

Check out `api/schemas/Agent.py` and `api/types/Agent.py` to see how the parameters passed from a parent entity in the graph are passed down to children.

Also In the latest `api-refactoring` commits I've refactored into `types` separate from `schemas` and named things with a `*Type` suffix again, as "Type" has a particular name in GraphQL and I think this helps us to make sense of the code. I've gone back to `*Type` for the API class names, but I might comb back over and put those back as they were on my next pass to avoid using the same class names as are found in the core.

**Comment by fosterlynn** [comment]
@ivanminutillo Here is a new sample query which includes the resources owned by the project (organization).  You could probably improve the query with another fragment.

I'm following the pattern set above by @pospi , since we haven't figured out how to get it to do recursive graph patterns.  But this will get you some data for now. :)

```
fragment coreAgentFields on AgentBaseType {
  id
  name
  image
  note
  type
}

query ($token: String) {
  viewer(token: $token) {
    myAgent {
      ...coreAgentFields
      organizations {
        id
        name
        members {
          name
          image
        }
      }
    }
    organization(id: 80) {
      ...coreAgentFields
      members {
        name
        image        
      }
      ownedCurrencyEconomicResources {
        resourceType
        trackingIdentifier
        numericValue
        unit
      }
      ownedInventoryEconomicResources {
        resourceType
        trackingIdentifier
        numericValue
        unit
      }
    }
  }
}
```

**Comment by fosterlynn** [comment]
Added unfinished processes for a context agent, here is a sample query:
```
fragment coreAgentFields on AgentBaseType {
  id
  name
  image
  note
  type
}

query ($token: String) {
  viewer(token: $token) {
    organization(id: 80) {
      ...coreAgentFields
      members {
        name
        image        
      }
      unfinishedProcesses {
        id
        name
      }
    }
  }
}
```

There are more fields available on Process if needed.

**Comment by pospi** [comment]
Closing this one- what we've done totally works
