### ISSUE TITLE
Process page separate inputs

### ISSUE THREAD

**Issue by fosterlynn** [django-rea/rea-app#64]
@ivanminutillo here is an example with other inputs besides work.  It seems like all inputs are being put under "works" (which would be better as "work" in English), instead of separating out the other inputs (consuming, using, citing).  Let me know if that is an api bug.

Also, it is useful to list the possible resources available for non-work inputs, if there are any.  Then people can just pick.

![new-ui-product](https://user-images.githubusercontent.com/3776081/28676065-47e2bb3c-72af-11e7-93fc-b8217fbfecdb.png)

![proc-log-product](https://user-images.githubusercontent.com/3776081/28676067-49e4798e-72af-11e7-9151-d8ac79e577cc.png)

**Comment by fosterlynn** [comment]
Actually, in this one it looks like the production commitment has also crept into the work section also.

![new-ui-out](https://user-images.githubusercontent.com/3776081/28676640-c5e393de-72b0-11e7-853c-5bf2432cbab4.png)

**Comment by ivanminutillo** [comment]
What is the production commitment in this last example?

**Comment by fosterlynn** [comment]
> What is the production commitment in this last example?

Produce 1 Each Technical or Support Deliverable - it shows up 2 places, look for the description "Project set up, roadmap clear...."

**Comment by ivanminutillo** [comment]
weird behaviour o_0

**Comment by ivanminutillo** [comment]
added 👍
