### ISSUE TITLE
continuous Integration & Staging server

### ISSUE THREAD

**Issue by ivanminutillo** [django-rea/rea-app#68]
How do we want to setup a continuous integration strategy and a live staging server?
We talked about this issue on the assembly but we didn't define a definitive implementation.

**Comment by XaviP** [comment]
Continous integration is working in freedomcoop/valuenetwork repo each time somebody pushes in any branch or a pull request is opened. So, for example, in branch api-extensions you can see a check sign in every commit:
https://github.com/FreedomCoop/valuenetwork/commits/api-extensions
If you click on the check (or red cross) sign, you go to travisci logs of the commit tests.

**Comment by ivanminutillo** [comment]
Can we have the same (or what is more appropriate) for the kamasi frontend?

**Comment by XaviP** [comment]
Travisci works with a config file .travis.yml in the root of the repo. Here the one in freeedomcoop/valuenetwork:
https://github.com/FreedomCoop/valuenetwork/blob/api-extensions/.travis.yml
For rea-app, you'll need to config with nodejs and all stuff you are using:
https://docs.travis-ci.com/user/getting-started/
Search in internet, there's a lot of info about howto setup it, and it's really easy.

**Comment by ivanminutillo** [comment]
Staging server was set up by @pospi and CI is on the roadmap so we can close this issue 👍
